
server:
  port: 9999
  servlet:
    context-path: /
spring:
  application:
    name: zuul-server
  redis:
    cluster:
      nodes: 192.168.44.70:7001,192.168.44.70:7001,192.168.44.70:7001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
zuul:
  routes:
    order-provider: /op/**
  ratelimit:
    enabled: true
    repository: redis
    default-policy-list:
        - limit: 2
          quota: 5
          refresh-interval: 10
          type:
            - origin
  ignored-services: order-consumer